-- Derived from the POLICY table DDL in base/cntl/db2cre.jcl.
-- H2 adjustments: identity options are space-separated instead of comma-separated; "NOT NULL WITH DEFAULT"
-- becomes "DEFAULT CURRENT_TIMESTAMP NOT NULL"; Db2-only clauses CCSID EBCDIC and IN <DB2DBID>.GENATS02 are
-- dropped; the separate CREATE UNIQUE INDEX iPolicy is omitted because the primary key already provides it.
-- The FOREIGN KEY to CUSTOMER is dropped: customers belong to customer-service, not this service.
CREATE TABLE policy (
     policyNumber     INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY
                       (START WITH 1000001 INCREMENT BY 1 CACHE 20),
     customerNumber   INTEGER NOT NULL,
     issueDate        DATE,
     expiryDate       DATE,
     policyType       CHAR(1),
     lastChanged      TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
     brokerId         INTEGER,
     brokersReference CHAR(10),
     payment          INTEGER,
     commission       SMALLINT,
   PRIMARY KEY(policyNumber));

CREATE INDEX iPolicy2 ON policy (customerNumber);
