-- Derived from the CUSTOMER table DDL in base/cntl/db2cre.jcl.
-- H2 adjustments: identity options are space-separated instead of comma-separated; Db2-only
-- clauses CCSID EBCDIC and IN <DB2DBID>.GENATS00 are dropped; the separate
-- CREATE UNIQUE INDEX iCustomer is omitted because the primary key already provides it.
CREATE TABLE customer (
     customerNumber INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY
                     (START WITH 1000001 INCREMENT BY 1 CACHE 20),
     firstName      CHAR(10),
     lastName       CHAR(20),
     dateOfBirth    DATE,
     houseName      CHAR(20),
     houseNumber    CHAR(4),
     postcode       CHAR(8),
     phonehome      CHAR(20),
     phonemobile    CHAR(20),
     emailaddress   CHAR(100),
   PRIMARY KEY(customerNumber));
